
server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1048710058652-pd9cp6p5lgpnflta00ssb2thm98ljv4b.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
          naver:
            client-id: fP69N0HJYtrDfwg8AKH6
            client-secret: THRzNWobuS
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            client-name: naver-client-app
            scope: profile, email
          kakao:
            client-id: 1c48487fb40821b0cfb451b1f0be54ee
            client-secret: 6fp8uOtJCvIZDMVoCkvW8hwzYJDmITSO
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-name: client-app
#            scope: openid, profile, account_email
#            scope: account_email, profile_nickname
            scope: account_email, profile_nickname, openid
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: sub
